53 adapt to voice over
bubble-jam-organization/bubble-jam pull request #63
Opened 2023-02-27 12:57 UTC by otavioalbucosta

2023-02-27 13:32 UTC, CaioFaSoares submitted a review, later dismissed

2023-02-28 12:27 UTC, ThiagoHBA requested changes
A gente viu que teve um problema no VoiceOver ligando enquanto tá tocando a música porque ele fala por cima. Uma possível solução pra isso é adicionar um botão de play na sheet quando o VoiceOver tiver ligado e deixar para o usuário a opção de tocar o som

2023-03-01 11:43 UTC, ThiagoHBA approved these changes

2023-03-01 11:50 UTC, CaioFaSoares approved these changes

2023-03-01 11:50 UTC, merged